const googleMapConsts = {
  SET_DEFAULT_CENTER: "SET_DEFAULT_CENTER",
  SET_CENTER: "SET_CENTER",
  SET_MAP_INFO: "SET_MAP_INFO",
  SET_GOOGLE_MAP_REF: "SET_GOOGLE_MAP_REF",
  PUSH_RESTAURANTS_TO_LIST: "PUSH_RESTAURANTS_TO_LIST"
};

export default googleMapConsts;
